### ISSUE TITLE
Issue running minitest_bisect

### ISSUE THREAD

**Issue by spartan218** [seattlerb/minitest-bisect#21]
I want to use this tool to debug intermittent test failures reported in a CI environment.

Currently I run the command `bundle exec rake test:api TESTOPTS=" -v --seed 6155"` to reproduce intermittent test failures.

I added `gem 'minitest-bisect'` and  `gem 'minitest-sprint'` to my Gemfile.

When I run the following command: `MTB_VERBOSE=2 bundle exec minitest_bisect --seed=6155 -Itest $(find test/api -type f -name \*_test.rb)`

I get this error 

```
reproducing.../Users/a_path/lib/mandrill.rb:134:in `<class:Scheduled>': uninitialized constant Mandrill::Scheduled::Scheduler (NameError)
	from /Users/a_path/lib/mandrill.rb:133:in `<module:Mandrill>'
	from /Users/a_path/lib/mandrill.rb:1:in `<top (required)>'
	from /nix/store/7lv7gmr0yy034znxchx8byb6ypnk48f0-bundler-1.17.2/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:81:in `require'
	from /nix/store/7lv7gmr0yy034znxchx8byb6ypnk48f0-bundler-1.17.2/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /nix/store/7lv7gmr0yy034znxchx8byb6ypnk48f0-bundler-1.17.2/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `each'
	from /nix/store/7lv7gmr0yy034znxchx8byb6ypnk48f0-bundler-1.17.2/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:76:in `block in require'
	from /nix/store/7lv7gmr0yy034znxchx8byb6ypnk48f0-bundler-1.17.2/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `each'
	from /nix/store/7lv7gmr0yy034znxchx8byb6ypnk48f0-bundler-1.17.2/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler/runtime.rb:65:in `require'
	from /nix/store/7lv7gmr0yy034znxchx8byb6ypnk48f0-bundler-1.17.2/lib/ruby/gems/2.3.0/gems/bundler-1.17.2/lib/bundler.rb:114:in `require'
	from /Users/a_path/config/application.rb:7:in `<top (required)>'
	from /Users/a_path/config/environment.rb:2:in `require'
	from /Users/a_path/config/environment.rb:2:in `<top (required)>'
	from /Users/a_path/test/test_helper.rb:2:in `require'
	from /Users/a_path/test/test_helper.rb:2:in `<top (required)>'
	from /Users/a_path/test/api/web/assets_test.rb:1:in `require'
	from /Users/a_path/test/api/web/assets_test.rb:1:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
```

Any help would be great.

**Comment by zenspider** [comment]
That's probably real and related to the code missing requires it needs for individual files to be loaded in any order. Take bisect out of this for a bit and just focus on rake and minitest-sprint. Your `find` command is running things in a different order than your `rake` command.

The quick way out of this is to run `rake test:api -t` to see the command output, and then convert that to a shell script using `minitest`. Assuming that loads fine, then you just switch to `minitest_bisect`.

The "right" way out of this is to ensure that each and every test file can be run by itself (and they should be able to... this is important). Run each one, add missing requires, repeat until done. (Don't worry about the test results—you'll probably find some of those failures this way—just get the tests running). Then the original command will work, but so will any subset in any order. I had to do this on chef/inspec when I started working on that because it made lots of assumptions about how/where it was running.

**Comment by spartan218** [comment]
@zenspider Thanks for suggestion. 

A clarifying question.. When I run the test standalone should I be doing so with `bundle exec rake` or `bundle exec ruby -Itest`.

I tried doing it with the latter and didn't see any errors like this.

It's helpful to know that there is a difference between the two so that running the same seed for both doesn't mean it will produce the same results. Thanks for the tips.

**Comment by zenspider** [comment]
`bundle exec` is a problem, because it auto-requires everything in your gemfile unless you say otherwise... but that might be a required part of your recipe as any of those things can use `rand` in a way that might change your lineup given your reproduction seed.

`rake` loads all of your files _in some particular order_ (depends on the filesystem you're on). This is necessary to reproduce your issue as that's how your CI (or whatever) did it.

Running with `bundle exec ruby` won't work unless your project only has one test file in it... so use `rake -t` to grab the command that rake runs to create an invocation with and convert it to use `minitest` and the list of test files _in the exact same order_. Once you can reproduce it that way, you can reproduce and isolate it using `minitest_bisect`.

**Comment by spartan218** [comment]
Got it running, the only problem I have now is that when it runs it aborts the reproduction without telling me why.

```
$ MTB_VERBOSE=2 bundle exec minitest_bisect some/dir/here/*.rb

/nix/store/5svvwcf445rfb2irn0n64lwi89wa1q41-ruby-2.3.8/bin/ruby -Itest:lib -e 'require "./some/dir/here/test_one.rb" ; require "./some/dir/here/test_two.rb" ; require "./some/dir/here/test_three.rb" ; require "./some/dir/here/test_three.rb"' -- --server 97714

reproducing... set_config 
------------
 
(1 row)

Run options: --server 97714 --seed 59628

# Running:

.................

Finished in 22.983740s, 0.7397 runs/s, 6.5699 assertions/s.

17 runs, 151 assertions, 0 failures, 0 errors, 0 skips
 in 59.32 sec
Reproduction run passed? Aborting.
Try running with MTB_VERBOSE=2 to verify.
```

**Comment by zenspider** [comment]
> it aborts the reproduction without telling me why

it does right here:

> Reproduction run passed? Aborting.
> Try running with MTB_VERBOSE=2 to verify.

**Comment by zenspider** [comment]
No response. Closing.
